[tool.black]
line-length = 88
target-version = ["py39"]
skip-string-normalization = true

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = ["__pycache__", ".venv", "venv", ".git"]